//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheProject.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheProject.Shared.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand must be informed..
        /// </summary>
        public static string BrandMustBeInformed {
            get {
                return ResourceManager.GetString("BrandMustBeInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer must be informed.
        /// </summary>
        public static string CustomerMustBeInformed {
            get {
                return ResourceManager.GetString("CustomerMustBeInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount max allowed is 10 percent..
        /// </summary>
        public static string DiscountMaxAllowed10Percent {
            get {
                return ResourceManager.GetString("DiscountMaxAllowed10Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Result.
        /// </summary>
        public static string HealthResult {
            get {
                return ResourceManager.GetString("HealthResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceId must be informed..
        /// </summary>
        public static string InvoiceIdMustBeInformed {
            get {
                return ResourceManager.GetString("InvoiceIdMustBeInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice does not exist..
        /// </summary>
        public static string InvoiceNotExist {
            get {
                return ResourceManager.GetString("InvoiceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be informed..
        /// </summary>
        public static string NameMustBeInformed {
            get {
                return ResourceManager.GetString("NameMustBeInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater or equals 0..
        /// </summary>
        public static string PriceMustBeGreaterOrEqualsZero {
            get {
                return ResourceManager.GetString("PriceMustBeGreaterOrEqualsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId must be informed..
        /// </summary>
        public static string ProductIdMustBeInformed {
            get {
                return ResourceManager.GetString("ProductIdMustBeInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product does not exist..
        /// </summary>
        public static string ProductNotExist {
            get {
                return ResourceManager.GetString("ProductNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be greater 0..
        /// </summary>
        public static string QuantityMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("QuantityMustBeGreaterThanZero", resourceCulture);
            }
        }
    }
}
